services:
  db:
    image: postgres:16
    container_name: 5k_v2_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 5k_tracker_v2
    ports:
      - "5432:5432"
    volumes:
      - pgdata_v2:/var/lib/postgresql/data
volumes:
  pgdata_v2: