version: '3.8'

services:
  # Database for tracker
  db:
    image: postgres:15
    container_name: tracker-db-dev
    environment:
      POSTGRES_DB: racetracker
      POSTGRES_USER: racetracker
      POSTGRES_PASSWORD: racetracker
    ports:
      - "5433:5432"
    volumes:
      - tracker_pgdata_dev:/var/lib/postgresql/data
    restart: unless-stopped

  # Dashboard - Main monitoring interface
  dashboard:
    build:
      context: ../
      dockerfile: apps/dashboard/Dockerfile
    container_name: dashboard-dev
    ports:
      - "5550:5550"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - DASHBOARD_USER=admin
      - DASHBOARD_PASS=fredrules
    volumes:
      - ../shared/ssl:/app/ssl:ro
      - ../shared/templates:/app/shared_templates:ro
    restart: unless-stopped

  # 5K Tracker
  tracker:
    build:
      context: ../apps/5k-tracker
      dockerfile: Dockerfile
    container_name: tracker-dev
    ports:
      - "5554:5554"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      - tracker_uploads_dev:/app/uploads
      - ../apps/5k-tracker:/app/source:ro
      - ../shared/ssl:/app/ssl:ro
    depends_on:
      - db
    restart: unless-stopped

  # 5K Tracker PWA
  pwa-tracker:
    build:
      context: ../apps/5k-tracker-pwa
      dockerfile: Dockerfile
    container_name: pwa-tracker-dev
    ports:
      - "5555:5555"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - TRACKER_DATABASE_URI=postgresql://racetracker:racetracker@db:5432/racetracker
    volumes:
      - tracker_uploads_dev:/app/uploads
      - ../apps/5k-tracker-pwa:/app/source:ro
      - ../shared/ssl:/app/ssl:ro
    depends_on:
      - db
    restart: unless-stopped

  # Cruise Price Check
  cruise-price-check:
    build:
      context: ../apps/cruise-price-check
      dockerfile: Dockerfile
    container_name: cruise-price-check-dev
    ports:
      - "5551:5551"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - CRUISE_DB_PATH=/app/data/cruise_prices.db
    volumes:
      - cruise_data_dev:/app/data
      - cruise_logs_dev:/app/logs
      - ../apps/cruise-price-check:/app/source:ro
      - ../shared/ssl:/app/ssl:ro
    restart: unless-stopped

  # Clan Map
  clan-map:
    build:
      context: ../apps/clan-map
      dockerfile: Dockerfile
    container_name: clan-map-dev
    ports:
      - "5552:5552"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      - ../apps/clan-map:/app/source:ro
      - ../shared/ssl:/app/ssl:ro
    restart: unless-stopped

  # QSL Card Creator
  qsl-card-creator:
    build:
      context: ../apps/W5XY-QSL-CARD-CREATOR
      dockerfile: Dockerfile
    container_name: qsl-card-creator-dev
    ports:
      - "5553:5553"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - QSL_DATABASE_PATH=/app/Log4OM\ db.SQLite
    volumes:
      - ../apps/W5XY-QSL-CARD-CREATOR:/app/source:ro
      - ../shared/ssl:/app/ssl:ro
    restart: unless-stopped

  # COC Discord Bot (optional for development)
  coc-discord-bot:
    build:
      context: ../apps/coc-discord-bot
      dockerfile: Dockerfile
    container_name: coc-discord-bot-dev
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      - ../apps/coc-discord-bot:/app/source:ro
      - ../shared/ssl:/app/ssl:ro
    profiles: ["with-bot"]  # Only start with: docker compose --profile with-bot up
    restart: unless-stopped

volumes:
  tracker_pgdata_dev:
  tracker_uploads_dev:
  cruise_data_dev:
  cruise_logs_dev:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500
