services:
  db:
    image: postgres:15
    container_name: tracker-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: racetracker
      POSTGRES_USER: racetracker
      POSTGRES_PASSWORD: racetracker
    volumes:
      - tracker_pgdata:/var/lib/postgresql/data

  cruise-price-check:
    build:
      context: ../apps/cruise-price-check
      dockerfile: Dockerfile
    container_name: cruise-price-check
    ports:
      - "5551:5551"
    restart: unless-stopped
    env_file:
      - ../shared/config/.env
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
      - CRUISE_DB_PATH=/app/data/cruise_prices.db
    volumes:
      - ../shared/ssl:/app/ssl:ro
      - ../shared/config:/app/config:ro
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.7'
        reservations:
          memory: 256M
          cpus: '0.3'
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5551/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  dashboard:
    build:
      context: ../
      dockerfile: apps/dashboard/Dockerfile
    container_name: dashboard
    ports:
      - "5550:5550"
    restart: unless-stopped
    env_file:
      - ../shared/config/.env
    environment:
      - DASHBOARD_USER=admin
      - DASHBOARD_PASS=fredrules
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
    volumes:
      - ../shared/ssl:/app/ssl:ro
      - ../shared/templates:/app/shared_templates:ro
      - /var/run/docker.sock:/var/run/docker.sock

  clan-map:
    build:
      context: ../apps/clan-map
      dockerfile: Dockerfile
    container_name: clan-map
    ports:
      - "5552:5552"
    restart: unless-stopped
    env_file:
      - ../shared/config/.env
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
    volumes:
      - ../shared/ssl:/app/ssl:ro
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5552/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  qsl-card-creator:
    build:
      context: ../apps/W5XY-QSL-CARD-CREATOR
      dockerfile: Dockerfile
    container_name: qsl-card-creator
    ports:
      - "5553:5553"
    restart: unless-stopped
    env_file:
      - ../shared/config/.env
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
      - QSL_DATABASE_PATH=/app/Log4OM\ db.SQLite
    volumes:
      - ../shared/ssl:/app/ssl:ro
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.7'
        reservations:
          memory: 256M
          cpus: '0.3'
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5553/status')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  tracker:
    build:
      context: ../apps/5k-tracker
      dockerfile: Dockerfile
    container_name: tracker
    ports:
      - "5554:5554"
    restart: unless-stopped
    env_file:
      - ../shared/config/.env
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
    volumes:
      - tracker_uploads:/app/uploads
      - ../shared/ssl:/app/ssl:ro
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5554/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  pwa-tracker:
    build:
      context: ../apps/5k-tracker-pwa
      dockerfile: Dockerfile
    container_name: pwa-tracker
    ports:
      - "5555:5555"
    restart: unless-stopped
    env_file:
      - ../shared/config/.env
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
    volumes:
      - tracker_uploads:/app/uploads
      - ../shared/ssl:/app/ssl:ro
    depends_on:
      - db
    networks:
      - default

  coc-discord-bot:
    build:
      context: ../apps/coc-discord-bot
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ../shared/config/.env
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
    volumes:
      - ../shared/config:/app/config:ro
      - ../shared/ssl:/app/ssl:ro
    healthcheck:
      test: ["CMD", "python", "config.py", "--healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    profiles: ["monitoring"]

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    restart: unless-stopped
    profiles: ["monitoring"]

volumes:
  cruise_data:
  cruise_logs:
  tracker_pgdata:
  tracker_uploads:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500
# Last updated: Wed Jul 30 17:19:51 CDT 2025
# Last updated: Wed Jul 30 17:21:33 CDT 2025
# Last updated: Wed Jul 30 17:21:48 CDT 2025
# Last updated: Wed Jul 30 17:53:59 CDT 2025
# Last updated: Wed Jul 30 17:55:01 CDT 2025
# Last updated: Wed Jul 30 17:59:33 CDT 2025
# Last updated: Wed Jul 30 18:03:08 CDT 2025
# Last updated: Wed Jul 30 18:08:22 CDT 2025
# Last updated: Wed Jul 30 22:29:56 CDT 2025
# Last updated: Wed Jul 30 22:37:13 CDT 2025
