-- SQL restore for bonus_history from May 2025 backup
-- Each player gets N records, with the last on the provided date, earlier ones spaced 30 days apart

INSERT INTO bonus_history (player_name, player_tag, awarded_date, awarded_by, bonus_type, notes) VALUES
('Death', '#CCGRUL82', '2025-01-01', 'system_restore', 'manual_restore', 'Restored from backup'),
('dnp', '#8GLLP9Q2', '2025-01-01', 'system_restore', 'manual_restore', 'Restored from backup'),
('Klee', '#GCYG8LLP', '2025-01-01', 'system_restore', 'manual_restore', 'Restored from backup'),
('natey', '#P8P8QY8J', '2025-02-01', 'system_restore', 'manual_restore', 'Restored from backup'),
('U Turn', '#GRRLR08R', '2025-02-01', 'system_restore', 'manual_restore', 'Restored from backup'),
('Mason', '#R9YVQGR8', '2025-02-01', 'system_restore', 'manual_restore', 'Restored from backup'),
('wes', '#YPJJG92Q', '2025-02-01', 'system_restore', 'manual_restore', 'Restored from backup'),
('Ray', '#GL2Q0UY', '2025-02-01', 'system_restore', 'manual_restore', 'Restored from backup'),
('J3N', '#Q22GRG9CU', '2025-02-01', 'system_restore', 'manual_restore', 'Restored from backup'),
('Pirate', '#QUJPYVJ0R', '2025-02-01', 'system_restore', 'manual_restore', 'Restored from backup'),
('Mama Squirrel', '#28C0JCPV0', '2025-02-01', 'system_restore', 'manual_restore', 'Restored from backup'),
('Foo Fighter', '#29GQURJU8', '2025-02-01', 'system_restore', 'manual_restore', 'Restored from backup'),
('noslos', '#RPPU8Y00', '2025-03-09', 'system_restore', 'manual_restore', 'Restored from backup'),
('cocmaster', '#2VL8VCQYQ', '2025-03-09', 'system_restore', 'manual_restore', 'Restored from backup'),
('jo', '#QGPRL2J0', '2025-03-09', 'system_restore', 'manual_restore', 'Restored from backup'),
('Souls-On-Fire', '#20JGQRRY', '2025-03-09', 'system_restore', 'manual_restore', 'Restored from backup'),
('MachZero', '#LYJY9PRU', '2025-03-09', 'system_restore', 'manual_restore', 'Restored from backup'),
('Paddington bear', '#2990VUYCU', '2025-03-09', 'system_restore', 'manual_restore', 'Restored from backup'),
('shz06', '#99VYLCJ', '2025-03-09', 'system_restore', 'manual_restore', 'Restored from backup'),
('moose40', '#G882J80Y', '2025-03-09', 'system_restore', 'manual_restore', 'Restored from backup'),
('Ivan Drago', '#22PC8PUP', '2025-03-09', 'system_restore', 'manual_restore', 'Restored from backup'),
('jcollind', '#QCYULVVQC', '2025-04-09', 'system_restore', 'manual_restore', 'Restored from backup'),
('ronnie', '#8VQQQ8UP', '2025-05-12', 'system_restore', 'manual_restore', 'Restored from backup'),
('Yancmo', '#2YUPQQ9L', '2025-03-09', 'system_restore', 'manual_restore', 'Restored from backup'),
('Yancmo', '#2YUPQQ9L', '2025-04-09', 'system_restore', 'manual_restore', 'Restored from backup'),
('knightress', '#LCPJCQJGY', '2025-03-09', 'system_restore', 'manual_restore', 'Restored from backup'),
('knightress', '#LCPJCQJGY', '2025-04-09', 'system_restore', 'manual_restore', 'Restored from backup'),
('anarchy125', '#R8VLCVQ9', '2025-03-09', 'system_restore', 'manual_restore', 'Restored from backup'),
('anarchy125', '#R8VLCVQ9', '2025-04-09', 'system_restore', 'manual_restore', 'Restored from backup'),
('Mini Me', '#UCP9QPC9', '2025-03-09', 'system_restore', 'manual_restore', 'Restored from backup'),
('Mini Me', '#UCP9QPC9', '2025-04-09', 'system_restore', 'manual_restore', 'Restored from backup'),
('/tps', '#RYQQR8VY', '2025-03-09', 'system_restore', 'manual_restore', 'Restored from backup'),
('/tps', '#RYQQR8VY', '2025-04-09', 'system_restore', 'manual_restore', 'Restored from backup'),
('dad', '#CQVJC9CV', '2025-03-09', 'system_restore', 'manual_restore', 'Restored from backup'),
('dad', '#CQVJC9CV', '2025-04-09', 'system_restore', 'manual_restore', 'Restored from backup'),
('RMax', '#VLRGJVRL', '2025-04-12', 'system_restore', 'manual_restore', 'Restored from backup'),
('RMax', '#VLRGJVRL', '2025-05-12', 'system_restore', 'manual_restore', 'Restored from backup'),
('LtCol Dad', '#29YCGQU2', '2025-04-12', 'system_restore', 'manual_restore', 'Restored from backup'),
('LtCol Dad', '#29YCGQU2', '2025-05-12', 'system_restore', 'manual_restore', 'Restored from backup'),
('Zeponomous', '#2CVYY9J0J', '2025-04-12', 'system_restore', 'manual_restore', 'Restored from backup'),
('Zeponomous', '#2CVYY9J0J', '2025-05-12', 'system_restore', 'manual_restore', 'Restored from backup'),
('Amber', '#9CQJ299Q', '2025-04-12', 'system_restore', 'manual_restore', 'Restored from backup'),
('Amber', '#9CQJ299Q', '2025-05-12', 'system_restore', 'manual_restore', 'Restored from backup');
