version: '3.8'
services:
  coc-discord-bot:
    build: .
    container_name: coc-discord-bot-dev
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - BOT_ENV=development
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - DISCORD_BOT_TOKEN=DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - CLAN_TAG=#PCRV2R2P
      - DISCORD_GUILD_ID=403910977302822913
      - LEADER_ROLE_ID=your_dev_leader_role_id
      - SUPERCELL_API_TOKEN=${SUPERCELL_API_TOKEN}
      - ADMIN_EMAIL=yancmo@gmail.com
      - ADMIN_DISCORD_ID=987654321098765432
      - GMAIL_USER=your_dev_gmail_user
      - GMAIL_PASS=your_dev_gmail_pass
    volumes:
      - ./config:/app/config:ro
      - .:/app
      - ../ssl:/app/ssl:ro
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "config.py", "--healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15
    container_name: cocstack-postgres-dev
    restart: unless-stopped
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser"]

volumes:
  postgres_data_dev:
