#!/bin/bash
# commit_all_apps.sh
# Auto-commit and push all app repos in the stack with autogenerated messages

for dir in */ ; do
  if [ -d "$dir/.git" ]; then
    echo "Processing $dir"
    cd "$dir"
    git add .
    CHANGES=$(git status --porcelain)
    if [ -n "$CHANGES" ]; then
      MSG="Auto-commit: $(git status -s | wc -l) change(s) in $dir on $(date '+%Y-%m-%d %H:%M:%S')"
      git commit -m "$MSG"
      git push
      echo "Committed and pushed in $dir"
    else
      echo "No changes to commit in $dir"
    fi
    cd ..
  else
    echo "$dir is not a git repo, skipping."
  fi
done
