version: '3.8'

services:
  crumb:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      # Optional: mount a volume for logs
      - ./logs:/app/logs

networks:
  default:
    name: crumb-network